name: Test

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    uses: dmptrluke/workflows/.github/workflows/django-lint.yml@main

  test:
    uses: dmptrluke/workflows/.github/workflows/django-test.yml@main
    with:
      matrix: >-
        [
          {"python": "3.10", "django": "4.2"},
          {"python": "3.12", "django": "4.2"},
          {"python": "3.12", "django": "5.2"},
          {"python": "3.13", "django": "5.2"},
          {"python": "3.14", "django": "5.2"},
          {"python": "3.12", "django": "6.0"},
          {"python": "3.13", "django": "6.0"},
          {"python": "3.14", "django": "6.0"}
        ]
